extend type Query {
  """
  ✨ Look up a single `Course` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  course(
    """
    The key used to identify the object.
    """
    key: Course_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Course_FirstRow
  ): Course @fdc_generated(from: "Course", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Enrollment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  enrollment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Enrollment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Enrollment_FirstRow
  ): Enrollment @fdc_generated(from: "Enrollment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ScheduleGroup` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  scheduleGroup(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ScheduleGroup_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ScheduleGroup_FirstRow
  ): ScheduleGroup @fdc_generated(from: "ScheduleGroup", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Student` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  student(
    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student @fdc_generated(from: "Student", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `StudyTask` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  studyTask(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: StudyTask_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: StudyTask_FirstRow
  ): StudyTask @fdc_generated(from: "StudyTask", purpose: QUERY_SINGLE)
  """
  ✨ List `Course` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  courses(
    """
    Filter condition to narrow down the query results.
    """
    where: Course_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Course_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Course_Having
  ): [Course!]! @fdc_generated(from: "Course", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Enrollment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  enrollments(
    """
    Filter condition to narrow down the query results.
    """
    where: Enrollment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Enrollment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Enrollment_Having
  ): [Enrollment!]! @fdc_generated(from: "Enrollment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ScheduleGroup` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  scheduleGroups(
    """
    Filter condition to narrow down the query results.
    """
    where: ScheduleGroup_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ScheduleGroup_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ScheduleGroup_Having
  ): [ScheduleGroup!]! @fdc_generated(from: "ScheduleGroup", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Student` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  students(
    """
    Filter condition to narrow down the query results.
    """
    where: Student_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Student_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Student_Having
  ): [Student!]! @fdc_generated(from: "Student", purpose: QUERY_MULTIPLE)
  """
  ✨ List `StudyTask` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  studyTasks(
    """
    Filter condition to narrow down the query results.
    """
    where: StudyTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [StudyTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: StudyTask_Having
  ): [StudyTask!]! @fdc_generated(from: "StudyTask", purpose: QUERY_MULTIPLE)
}
